{{- range $db := .Values.databases }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.project }}-{{ $db.name }}-secret
  namespace: {{ $.Values.project }}
  annotations:
    argocd.argoproj.io/sync-options: Validate=false,SkipDryRunOnMissingResource=true,Replace=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/hook: "Skip"
    argocd.argoproj.io/reconcile-strategy: "none"
type: Opaque
data:
  password: {{ randAlphaNum 16 | b64enc }}
immutable: true
{{- end }}
