{{- range $db := .Values.databases }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.project }}-{{ $db.name }}-secret
  namespace: {{ $.Values.project }}
  annotations:
    argocd.argoproj.io/sync-options: Validate=false,SkipDryRunOnMissingResource=true
type: Opaque
data:
  password: {{ randAlphaNum 16 | b64enc }}
immutable: true
{{- end }}
