{{- range $db := .Values.databases }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.project }}-{{ $db.name }}-secret
  namespace: {{ $.Values.project }}
  annotations:
    "argocd.argoproj.io/compare-options": "IgnoreExtraneous"
    "helm.sh/resource-policy": "keep"
    "argocd.argoproj.io/sync-options": "Skip"
    # "helm.sh/hook": "pre-install"
    # "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  password: {{ randAlphaNum 16 | b64enc }}
immutable: true
{{- end }}
