{{- range $db := .Values.databases }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.project }}-{{ $db.name }}-secret
  namespace: {{ $.Values.project }}
  annotations:
    "argocd.argoproj.io/compare-options": "IgnoreExtraneous"
    # Git에 정의되지 않은 추가적인 필드들을 무시합니다.
    # 즉, 실제 클러스터의 시크릿에 추가 데이터가 있어도 차이로 감지하지 않습니다.
  
    "helm.sh/resource-policy": "keep"
    # Helm이 이 리소스를 삭제하지 않도록 합니다.
    # helm uninstall을 실행해도 이 리소스는 유지됩니다.
  
    "argocd.argoproj.io/sync-options": "Skip"
    # ArgoCD가 이 리소스를 동기화 작업에서 완전히 제외합니다.
    # 즉, Git과 클러스터 간의 차이를 무시합니다.
  
    "argocd.argoproj.io/sync-wave": "-1"
    # 동기화 순서를 지정합니다. 낮은 숫자가 먼저 동기화됩니다.
    # -1은 가장 먼저 처리된다는 의미입니다.
  
    "argocd.argoproj.io/sync-options": "Prune=false"
    # 리소스가 Git에서 제거되어도 클러스터에서 삭제하지 않습니다.
type: Opaque
data:
  password: {{ randAlphaNum 16 | b64enc }}
immutable: true
{{- end }}
