apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/injunweb/projects-gitops.git
        revision: HEAD
        files:
          - path: "projects/*.yaml"
  template:
    metadata:
      name: "{{path.filename}}"
      namespace: argocd
    spec:
      project: "default"
      source:
        repoURL: https://github.com/injunweb/projects-gitops.git
        targetRevision: HEAD
        path: charts
        helm:
          valueFiles:
            - "{{path.path}}"
          values: |
            project: "{{path.filename}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.filenameNormalized | trimSuffix ".yaml"}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
