apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/injunweb/projects-gitops.git
        revision: HEAD
        files:
          - path: "projects/*.yaml"
  template:
    metadata:
      # 파일 이름만 추출
      name: "{{`{{basename path}}`}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/injunweb/projects-gitops.git
        targetRevision: HEAD
        path: charts
        helm:
          valueFiles:
            - ../projects/{{`{{basename path}}`}}
          values: |
            project: "{{`{{basename path}}`}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{`{{basename path}}`}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
