apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: projects-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/injunweb/projects-gitops.git
        revision: HEAD
        files:
          - path: "projects/*.yaml"
  template:
    metadata:
      name: '{{.path.filenameNormalized | trimSuffix ".yaml"}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/injunweb/projects-gitops.git
        targetRevision: HEAD
        path: chart
        plugin:
          name: argocd-vault-plugin-helm
          env:
            - name: HELM_ARGS
              value: >-
                -f ../projects/{{.path.filename}}
                --set project={{.path.filenameNormalized | trimSuffix ".yaml"}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.filenameNormalized | trimSuffix ".yaml"}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
