{{- range $app := .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: {{ $.Values.project }}-{{ $app.name }}-github
  namespace: {{ $.Values.project }}
spec:
  template:
    serviceAccountName: argo-events-sa
  service:
    ports:
      - port: 12000
        targetPort: 12000
        name: webhook
  github:
    {{ $app.name }}-github:
      repositories:
        - owner: {{ $app.ghOwner }}
          names:
            - {{ $app.ghRepo }}
      webhook:
        endpoint: /{{ $.Values.project }}-{{ $app.name }}
        port: "12000"
        method: POST
        url: https://webhook.injunweb.com/{{ $.Values.project }}-{{ $app.name }}
      events:
        - push
        - delete
      apiToken:
        name: github-secret
        key: token
      insecure: false
      active: true
      contentType: json
{{- end }}