---
# Source: applications/templates/networkpolicy.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: comment-networkpolicy
  namespace: comment
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 192.168.0.0/16
              - 10.0.0.0/8
    - namespaceSelector:
        matchLabels:
          internal: "true"
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 192.168.0.0/16
              - 10.0.0.0/8
        - namespaceSelector:
            matchLabels:
              internal: "true"
---
# Source: applications/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: comment-account
  namespace: comment
---
# Source: applications/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: comment-service
  namespace: comment
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: comment
  type: ClusterIP
---
# Source: applications/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment
  namespace: comment
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: comment
  template:
    metadata:
      labels:
        app: comment
    spec:
      serviceAccountName: comment-account
      containers:
        - name: comment
          image: admin-harbor.injunweb.com/injunweb/comment:321498d
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: comment
          resources:
            requests:
              memory: "256Mi"
              cpu: "5m"
            limits:
              memory: "512Mi"
              cpu: "50m"
      imagePullSecrets:
        - name: imagepullsecret
---
# Source: applications/templates/ingressroute.yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: comment-ingressroute
  namespace: comment
spec:
  entryPoints:
    - web
  routes:
    - match: >
        Host(`comment.injunweb.com`)
      kind: Rule
      services:
        - name: comment-service
          port: 80
      middlewares:
        - name: comment-ratelimit
        - name: comment-buffering
---
# Source: applications/templates/middleware.yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: comment-ratelimit
  namespace: comment
spec:
  rateLimit:
    average: 30
    burst: 35
    period: 1m
    sourceCriterion:
      ipStrategy:
        depth: 1
---
# Source: applications/templates/middleware.yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: comment-buffering
  namespace: comment
spec:
  buffering:
    maxRequestBodyBytes: 1000000
    memRequestBodyBytes: 500000
    maxResponseBodyBytes: 2000000
    memResponseBodyBytes: 1000000
    retryExpression: "IsNetworkError() && Attempts() <= 2"
---
# Source: applications/templates/vault-auth.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: comment-auth
  namespace: comment
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: injunweb-role
    serviceAccount: comment-account
    audiences:
      - vault
---
# Source: applications/templates/vault-static-secret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: comment-secret
  namespace: comment
spec:
  type: kv-v1
  mount: injunweb-kv
  path: comment
  destination:
    name: comment
    create: true
  vaultAuthRef: comment/comment-auth
  refreshAfter: 1m
  rolloutRestartTargets:
    - kind: Deployment
      name: comment
