---
# Source: applications/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: comment-account
  namespace: comment
---
# Source: applications/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: comment-service
  namespace: comment
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: comment
  type: ClusterIP
---
# Source: applications/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment
  namespace: comment
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: comment
  template:
    metadata:
      labels:
        app: comment
    spec:
      serviceAccountName: comment-account
      containers:
        - name: comment
          image: admin-harbor.injunweb.com/injunweb/comment:db925ab
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: comment
          resources:
            requests:
              memory: "2000Mi"
              cpu: "20m"
            limits:
              memory: "2000Mi"
              cpu: "100m"
      imagePullSecrets:
        - name: imagepullsecret
---
# Source: applications/templates/ingressroute.yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: comment-ingressroute
  namespace: comment
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`comment.injunweb.com`)
      kind: Rule
      services:
        - name: comment-service
          port: 80
---
# Source: applications/templates/vault-auth.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: comment-auth
  namespace: comment
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: injunweb-role
    serviceAccount: comment-account
    audiences:
      - vault
---
# Source: applications/templates/vault-static-secret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: comment-secret
  namespace: comment
spec:
  type: kv-v1
  mount: injunweb-kv
  path: comment
  destination:
    name: comment
    create: true
  vaultAuthRef: comment/comment-auth
  refreshAfter: 1m
  rolloutRestartTargets:
    - kind: Deployment
      name: comment
