apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.project }}-ci-workflow-sa
  namespace: {{ $.Values.project }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $.Values.project }}-ci-workflow-role
  namespace: {{ $.Values.project }}
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflows", "workflowtemplates", "workflowtaskresults"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $.Values.project }}-ci-workflow-rolebinding
  namespace: {{ $.Values.project }}
subjects:
  - kind: ServiceAccount
    name: {{ $.Values.project }}-ci-workflow-sa
    namespace: {{ $.Values.project }}
roleRef:
  kind: Role
  name: {{ $.Values.project }}-ci-workflow-role
  apiGroup: rbac.authorization.k8s.io
