apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.project }}-github-access-secret
  namespace: {{ .Values.project }}
type: Opaque
data:
  username: "<path:argocd/data/github#username>"
  token: "<path:argocd/data/github#token>"
