{{- range $app := .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: {{ $.Values.project }}-{{ $app.name }}-github-workflow-sensor
  namespace: {{ $.Values.project }}
spec:
  eventBusName: {{ $.Values.project }}-ci-eventbus
  template:
    serviceAccountName: {{ $.Values.project }}-ci-workflow-sa
  dependencies:
    - name: github-dep
      eventSourceName: {{ $.Values.project }}-{{ $app.name }}-github-eventsource
      eventName: {{ $.Values.project }}-{{ $app.name }}-github-trigger
      filters:
        data:
          - path: body.ref
            type: string
            comparator: "="
            value:
              - "refs/heads/{{ $app.git.branch }}"
  triggers:
    - template:
        name: workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: {{ $.Values.project }}-{{ $app.name }}-build-workflow-
              spec:
                workflowTemplateRef:
                  name: {{ $.Values.project }}-{{ $app.name }}-build-workflow-template
{{- end }}
