apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: {{ .Values.project }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "<path:argocd/data/harbor#dockerconfigjson>"
