---
# Source: gocd/templates/deploy.yaml
format_version: 10
pipelines:
  build-github-profile-comments:
    group: injunweb

    label_template: "${git[:7]}"

    environment_variables:
      IMAGE_TAG: "${GO_PIPELINE_LABEL}"
      HARBOR_URL: admin-harbor.injunweb.com
      GOCD_HARBOR_USER: gocd-pusher
      K8S_HARBOR_USER: k8s-reader
      GITHUB_USER: in-jun

    secure_variables:
      GOCD_HARBOR_PASS: AES:NIt/x136N2Cu5hf7qg6eNw==:ELXteos0caMlG5ssCGbZtA==
      K8S_HARBOR_PASS: AES:8TpDXjrUTqWXOYTbEkcz6A==:98UDcRYcW31pQcMC5K8w/w==
      GITHUB_TOKEN: AES:OSKQMJLHd5J3k45gApjPxQ==:fLbIFcLx78WPuIzwPbhPkZiEynFMNAqb8JDTEe0xS2njikqd6tWqrtSY+H5SuKQj

    materials:
      git:
        git: "https://github.com/in-jun/github-profile-comments"
        shallow_clone: false
        auto_update: true
        branch: "main"

    stages:
      - build:
          clean_workspace: true
          jobs:
            build:
              timeout: 0
              fetch_materials: true
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - |
                        echo "Building Docker image for ${HARBOR_URL}/injunweb/github-profile-comments:$IMAGE_TAG ..."
                        docker build -t ${HARBOR_URL}/injunweb/github-profile-comments:$IMAGE_TAG .

                        if [ $? -eq 0 ]; then
                          echo "Docker build succeeded. Pushing image to Harbor..."
                          echo "${GOCD_HARBOR_PASS}" | docker login -u ${GOCD_HARBOR_USER} --password-stdin ${HARBOR_URL}
                          docker push ${HARBOR_URL}/injunweb/github-profile-comments:$IMAGE_TAG
                        else
                          echo "Docker build failed."
                          exit 1
                        fi

      - deploy:
          clean_workspace: true
          jobs:
            deploy:
              timeout: 0
              fetch_materials: true
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - |
                        echo "Cloning GitOps repository..."
                        git clone https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/injunweb/gitops-repo.git
                        cd gitops-repo

                        echo "Rendering Helm templates..."
                        helm template app ./templates/applications \
                          --values ./pipelines/github-profile-comments/values.yaml \
                          --set imageTag=$IMAGE_TAG > ./pipelines/github-profile-comments/manifests.yaml

                        echo "Committing Helm templates to GitOps repository..."
                        git config --global user.name "in-jun"
                        git config --global user.email "injuninjune@gmail.com"
                        git add ./pipelines/github-profile-comments/manifests.yaml
                        git commit -m "Updated Helm templates for github-profile-comments with imageTag $IMAGE_TAG"
                        git push https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/injunweb/gitops-repo.git

                        echo "Checking if namespace github-profile-comments exists..."
                        if ! kubectl get namespace github-profile-comments; then
                          echo "Namespace does not exist, creating it..."
                          kubectl create namespace github-profile-comments

                          echo "Creating imagePullSecrets..."
                          kubectl create secret docker-registry harbor-creds \
                            --docker-server=${HARBOR_URL} \
                            --docker-username=${K8S_HARBOR_USER} \
                            --docker-password=${K8S_HARBOR_PASS} \
                            --docker-email=k8s@k8s.com \
                            --namespace github-profile-comments || echo "Secret already exists."
                        else
                          echo "Namespace already exists."
                        fi

                        echo "Applying Kubernetes manifests..."
                        kubectl apply -f ./pipelines/github-profile-comments/manifests.yaml --namespace github-profile-comments

                        echo "Patching deployment with imagePullSecrets..."
                        kubectl patch deployment github-profile-comments \
                          -p '{"spec":{"template":{"spec":{"imagePullSecrets":[{"name":"harbor-creds"}]}}}}' \
                          --namespace github-profile-comments
