{{- range $app := .Values.applications }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: {{ $app.name }}-auth
  namespace: {{ $.Values.project }}
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: injunweb-role
    serviceAccount: {{ $app.name }}-sa
{{- end }}
