apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.appName }}
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      serviceAccountName: {{ .Values.appName }}-account
      containers:
        - name: {{ .Values.appName }}
          image: admin-harbor.injunweb.com/injunweb/{{ .Values.appName }}:{{ .Values.imageTag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.port }}
          envFrom:
          - secretRef:
              name: {{ .Values.appName }}
          resources:
            requests:
              memory: "2000Mi"
              cpu: "20m"
              ephemeral-storage: "20Mi"
            limits:
              memory: "2000Mi"
          readinessProbe:
            tcpSocket:
              port: {{ .Values.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 3
