apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.appName }}-ingressroute
  namespace: {{ .Values.appName }}
spec:
  entryPoints:
    - web
  routes:
    - match: >
        Host(`{{ .Values.customHostname | default (printf "%s.ijw.app" .Values.appName) }}`)
        {{- range .Values.additionalHostnames }} || Host(`{{ . }}`){{- end }}
      kind: Rule
      services:
        - name: {{ .Values.appName }}-service
          port: 80
      middlewares:
        - name: {{ .Values.appName }}-ratelimit
        - name: {{ .Values.appName }}-buffering