apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.appName }}-ratelimit
  namespace: {{ .Values.appName }}
spec:
  rateLimit:
    average: 10
    burst: 20
    period: 10s
    sourceCriterion:
      ipStrategy:
        depth: 1
    buckets: 1

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.appName }}-buffering
  namespace: {{ .Values.appName }}
spec:
  buffering:
    maxRequestBodyBytes: 1000000
    memRequestBodyBytes: 500000
    maxResponseBodyBytes: 2000000
    memResponseBodyBytes: 1000000
    retryExpression: "IsNetworkError() && Attempts() <= 2"