{{- if not .Values.disableInternalNetworkBlock }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.appName }}-networkpolicy
  namespace: {{ .Values.appName }}
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 192.168.0.0/16
      ports: []
{{- end }}
