{{- if not .Values.disableInternalNetworkBlock }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.appName }}-networkpolicy
  namespace: {{ .Values.appName }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 192.168.0.0/16
              - 10.0.0.0/8
    - namespaceSelector:
        matchLabels:
          internal: "true"
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 192.168.0.0/16
              - 10.0.0.0/8
        - namespaceSelector:
            matchLabels:
              internal: "true"
{{- end }}