apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
  namespace: {{ .Values.appName }}
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.port }}
  selector:
    app: {{ .Values.appName }}
  type: ClusterIP