apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: {{ .Values.appName }}-secret
  namespace: {{ .Values.appName }}
spec:
  mount: injunweb-kv
  path: {{ .Values.appName }}-v2
  destination:
    name: {{ .Values.appName }}
    create: true
  vaultAuthRef: {{ .Values.appName }}/{{ .Values.appName }}-auth
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ .Values.appName }}