apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: {{ .Values.appName }}-secret
  namespace: {{ .Values.appName }}
spec:
  mount: injunweb-kv
  path: {{ .Values.appName }}
  destination:
    name: {{ .Values.appName }}
    create: true
  renewalPercent: 60
  refreshAfter: 1m
  vaultAuthRef: {{ .Values.appName }}/{{ .Values.appName }}-auth
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ .Values.appName }}