{{- range $app := .Values.applications }}
{{- if and $app.tag $app.expose.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $app.name }}
  namespace: {{ $.Values.project }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`{{ $app.expose.primaryDomain }}`) && PathPrefix(`{{ $app.expose.path }}`)
      kind: Rule
      services:
        - name: {{ $app.name }}
          port: {{ $app.port }}
    {{- range $domain := $app.expose.additionalDomains }}
    - match: Host(`{{ $domain }}`) && PathPrefix(`{{ $app.expose.path }}`)
      kind: Rule
      services:
        - name: {{ $app.name }}
          port: {{ $app.port }}
    {{- end }}
{{- end }}
{{- end }}
