{{- range $app := .Values.applications }}
{{- if $app.imageTag }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $app.name }}
  namespace: {{ $.Values.project }}
spec:
  ports:
  - port: {{ $app.port }}
    targetPort: {{ $app.port }}
  selector:
    app: {{ $app.name }}
{{- end }}
{{- end }}
