{{- range $app := .Values.applications }}
{{- if $app.git.hash }}
{{- range $domain := $app.domains }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $.Values.project }}-{{ $app.name }}-{{ $domain | replace "." "-" }}-route
  namespace: {{ $.Values.project }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`{{ $domain }}`) 
      kind: Rule
      services:
        - name: {{ $app.name }}
          port: {{ $app.port }}
{{- end }}
{{- end }}
{{- end }}
