---
# Source: applications/templates/networkpolicy.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: file-server-networkpolicy
  namespace: file-server
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 192.168.0.0/16
              - 10.244.0.0/16
              - 10.96.0.0/12
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
    - from:
        - namespaceSelector:
            matchLabels:
              internal: "true"
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 192.168.0.0/16
              - 10.244.0.0/16
              - 10.96.0.0/12
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
    - to:
        - namespaceSelector:
            matchLabels:
              internal: "true"
---
# Source: applications/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: file-server-account
  namespace: file-server
---
# Source: applications/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: file-server-service
  namespace: file-server
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: file-server
  type: ClusterIP
---
# Source: applications/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-server
  namespace: file-server
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: file-server
  template:
    metadata:
      labels:
        app: file-server
    spec:
      serviceAccountName: file-server-account
      containers:
        - name: file-server
          image: admin-harbor.injunweb.com/injunweb/file-server:0cb9214
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: file-server
          resources:
            requests:
              memory: "256Mi"
              cpu: "5m"
            limits:
              memory: "512Mi"
              cpu: "50m"
      imagePullSecrets:
        - name: imagepullsecret
---
# Source: applications/templates/ingressroute.yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: file-server-ingressroute
  namespace: file-server
spec:
  entryPoints:
    - web
  routes:
    - match: >
        Host(`file-server.ijw.app`)
      kind: Rule
      services:
        - name: file-server-service
          port: 80
      middlewares:
        - name: file-server-ratelimit
        - name: file-server-buffering
---
# Source: applications/templates/middleware.yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: file-server-ratelimit
  namespace: file-server
spec:
  rateLimit:
    average: 30
    burst: 35
    period: 1m
    sourceCriterion:
      ipStrategy:
        depth: 1
---
# Source: applications/templates/middleware.yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: file-server-buffering
  namespace: file-server
spec:
  buffering:
    maxRequestBodyBytes: 1000000
    memRequestBodyBytes: 500000
    maxResponseBodyBytes: 2000000
    memResponseBodyBytes: 1000000
    retryExpression: "IsNetworkError() && Attempts() <= 2"
---
# Source: applications/templates/vault-auth.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: file-server-auth
  namespace: file-server
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: injunweb-role
    serviceAccount: file-server-account
    audiences:
      - vault
---
# Source: applications/templates/vault-static-secret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: file-server-secret
  namespace: file-server
spec:
  type: kv-v1
  mount: injunweb-kv
  path: file-server
  destination:
    name: file-server
    create: true
  vaultAuthRef: file-server/file-server-auth
  refreshAfter: 1m
  rolloutRestartTargets:
    - kind: Deployment
      name: file-server
