---
# Source: applications/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: asdf-account
  namespace: asdf
---
# Source: applications/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: asdf-service
  namespace: asdf
spec:
  ports:
    - port: 80
      targetPort: 9090
  selector:
    app: asdf
  type: ClusterIP
---
# Source: applications/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: asdf
  namespace: asdf
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: asdf
  template:
    metadata:
      labels:
        app: asdf
    spec:
      serviceAccountName: asdf-account
      containers:
        - name: asdf
          image: admin-harbor.injunweb.com/injunweb/asdf:808f1f7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          envFrom:
            - secretRef:
                name: asdf
          resources:
            requests:
              memory: "256Mi"
              cpu: "5m"
            limits:
              memory: "512Mi"
              cpu: "50m"
      imagePullSecrets:
        - name: imagepullsecret
---
# Source: applications/templates/ingressroute.yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: asdf-ingressroute
  namespace: asdf
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`asdf.injunweb.com`)
      kind: Rule
      services:
        - name: asdf-service
          port: 80
      middlewares:
        - name: asdf-ratelimit
        - name: asdf-buffering
---
# Source: applications/templates/middleware.yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: asdf-ratelimit
  namespace: asdf
spec:
  rateLimit:
    average: 30
    burst: 35
    period: 1m
    sourceCriterion:
      ipStrategy:
        depth: 1
---
# Source: applications/templates/middleware.yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: asdf-buffering
  namespace: asdf
spec:
  buffering:
    maxRequestBodyBytes: 1000000
    memRequestBodyBytes: 500000
    maxResponseBodyBytes: 2000000
    memResponseBodyBytes: 1000000
    retryExpression: "IsNetworkError() && Attempts() <= 2"
---
# Source: applications/templates/vault-auth.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: asdf-auth
  namespace: asdf
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: injunweb-role
    serviceAccount: asdf-account
    audiences:
      - vault
---
# Source: applications/templates/vault-static-secret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: asdf-secret
  namespace: asdf
spec:
  type: kv-v1
  mount: injunweb-kv
  path: asdf
  destination:
    name: asdf
    create: true
  vaultAuthRef: asdf/asdf-auth
  refreshAfter: 1m
  rolloutRestartTargets:
    - kind: Deployment
      name: asdf
