---
# Source: applications/templates/networkpolicy.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-networkpolicy
  namespace: api
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 192.168.0.0/16
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 192.168.0.0/16
---
# Source: applications/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-account
  namespace: api
---
# Source: applications/templates/cluster-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-role
  labels:
    app: api
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "create", "update", "delete"]
---
# Source: applications/templates/cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-rolebinding
  labels:
    app: api
subjects:
  - kind: ServiceAccount
    name: api-account
    namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: api-role
---
# Source: applications/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: api
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: api
  type: ClusterIP
---
# Source: applications/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: api
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccountName: api-account
      containers:
        - name: api
          image: admin-harbor.injunweb.com/injunweb/api:fa297df
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: api
          resources:
            requests:
              memory: "256Mi"
              cpu: "5m"
            limits:
              memory: "512Mi"
              cpu: "50m"
      imagePullSecrets:
        - name: imagepullsecret
---
# Source: applications/templates/ingressroute.yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: api-ingressroute
  namespace: api
spec:
  entryPoints:
    - web
  routes:
    - match: >
        Host(`api.injunweb.com`)
      kind: Rule
      services:
        - name: api-service
          port: 80
      middlewares:
        - name: api-ratelimit
        - name: api-buffering
---
# Source: applications/templates/middleware.yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: api-ratelimit
  namespace: api
spec:
  rateLimit:
    average: 30
    burst: 35
    period: 1m
    sourceCriterion:
      ipStrategy:
        depth: 1
---
# Source: applications/templates/middleware.yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: api-buffering
  namespace: api
spec:
  buffering:
    maxRequestBodyBytes: 1000000
    memRequestBodyBytes: 500000
    maxResponseBodyBytes: 2000000
    memResponseBodyBytes: 1000000
    retryExpression: "IsNetworkError() && Attempts() <= 2"
---
# Source: applications/templates/vault-auth.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: api-auth
  namespace: api
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: injunweb-role
    serviceAccount: api-account
    audiences:
      - vault
---
# Source: applications/templates/vault-static-secret.yaml
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: api-secret
  namespace: api
spec:
  type: kv-v1
  mount: injunweb-kv
  path: api
  destination:
    name: api
    create: true
  vaultAuthRef: api/api-auth
  refreshAfter: 1m
  rolloutRestartTargets:
    - kind: Deployment
      name: api
